### ISSUE TITLE
inference on single image?

### ISSUE THREAD

**Issue by ydzhang12345** [aatifjiwani/rgb-footprint-extract#3]
Hi,

Thanks for the great work! Would you please suggest how to run inference on a single image? I would like to test the model on my own urban satellite data. Thanks!

**Comment by aatifjiwani** [comment]
Apologies for being inactive for such a long time, I've been quite busy the past few weeks. Thank you so much @calebrob6 for resolving this! @ydzhang12345 I hope you were able to get what you needed!
