### ISSUE TITLE
pretrained model weights assume using GPU

### ISSUE THREAD

**Issue by calebrob6** [aatifjiwani/rgb-footprint-extract#6]
FYI -- the pretrained model weights don't work if you aren't using a GPU as the model is only wrapped in DataParallel when you have a GPU here -- https://github.com/aatifjiwani/rgb-footprint-extract/blob/main/models/deeplab/evaluate.py#L58

**Comment by aatifjiwani** [comment]
@calebrob6 Fixed in #7. If `--no-cuda` is passed in as a flag, then it will parse the weights to remove the `module.` prefix from the `DataParallel` wrapper.
