### ISSUE TITLE
sh test_deeplab.sh  ，How to visualize test results？

### ISSUE THREAD

**Issue by zhenghan408** [aatifjiwani/rgb-footprint-extract#9]

**Comment by zhenghan408** [comment]
i want to get Visualized picture.
can help me?
thank you~

**Comment by aatifjiwani** [comment]
Hi, I refer you to this open Pull Request: #5. This contains code to input a TIF image and get a TIF output image of the predicted segmentation mask. 

I will be making some additions to the master branch by the end of this week to implement this feature.

**Comment by aatifjiwani** [comment]
@zhenghan408 I have updated the repository with support for inference on Numpy files. I will be working on TIFF support soon.
